import {
  FaBuilding,
  FaLeaf,
  FaTshirt,
  FaMobileAlt,
  FaHome,
  FaFootballBall,
  FaSpa,
  FaTools,
  FaBoxOpen,
  FaGem,
  FaBaby,
  FaShoePrints,
  FaCar,
  FaCouch,
  FaIndustry,
  FaWrench,
  FaSuitcase,
  FaBlender,
  FaHammer,
  FaTruck,
  FaToolbox,
  FaBroom,
  FaLightbulb,
  FaGift,
  FaSolarPanel,
  FaHeartbeat,
  FaPlug,
  FaHardHat,
  FaSchool,
  FaMicrochip,
  FaStethoscope,
  FaUtensils,
  FaFlask,
  FaClipboardCheck,
  FaShieldAlt,
  FaDog,
  FaCogs,
  //   FaIndustryAlt,
  //   FaHardHat,
  FaShippingFast,
  FaRecycle,
  FaCog,
  FaSeedling,
} from "react-icons/fa";

const carouselItems = [
  { id: 1, text: "Business Services", icon: <FaBuilding /> },
  { id: 2, text: "Environment", icon: <FaLeaf /> },
  { id: 3, text: "Apparel & Accessories", icon: <FaTshirt /> },
  { id: 4, text: "Consumer Electronics", icon: <FaMobileAlt /> },
  { id: 5, text: "Home & Garden", icon: <FaHome /> },
  { id: 6, text: "Sports & Entertainment", icon: <FaFootballBall /> },
  { id: 7, text: "Beauty", icon: <FaSpa /> },
  { id: 8, text: "Commercial Equipment & Machinery", icon: <FaTools /> },
  { id: 9, text: "Packaging & Printing", icon: <FaBoxOpen /> },
  { id: 10, text: "Jewelry, Eyewear, Watches & Accessories", icon: <FaGem /> },
  { id: 11, text: "Mother, Kids & Toys", icon: <FaBaby /> },
  { id: 12, text: "Shoes & Accessories", icon: <FaShoePrints /> },
  { id: 13, text: "Vehicle Parts & Accessories", icon: <FaCar /> },
  { id: 14, text: "Furniture", icon: <FaCouch /> },
  { id: 15, text: "Industrial Machinery", icon: <FaIndustry /> },
  { id: 16, text: "Tools & Hardware", icon: <FaWrench /> },
  { id: 17, text: "Luggage, Bags & Cases", icon: <FaSuitcase /> },
  { id: 18, text: "Home Appliances", icon: <FaBlender /> },
  { id: 19, text: "Construction & Real Estate", icon: <FaHammer /> },
  { id: 20, text: "Vehicles & Transportation", icon: <FaTruck /> },
  {
    id: 21,
    text: "Vehicle Accessories, Electronics & Tools",
    icon: <FaToolbox />,
  },
  { id: 22, text: "Personal Care & Household Cleaning", icon: <FaBroom /> },
  { id: 23, text: "Lights & Lighting", icon: <FaLightbulb /> },
  { id: 24, text: "Gifts & Crafts", icon: <FaGift /> },
  { id: 25, text: "Renewable Energy", icon: <FaSolarPanel /> },
  { id: 26, text: "Health Care", icon: <FaHeartbeat /> },
  { id: 27, text: "Electrical Equipment & Supplies", icon: <FaPlug /> },
  { id: 28, text: "Construction & Building Machinery", icon: <FaHardHat /> },
  { id: 29, text: "School & Office Supplies", icon: <FaSchool /> },
  {
    id: 30,
    text: "Electronic Components, Accessories",
    icon: <FaMicrochip />,
  },
  { id: 31, text: "Medical Devices & Supplies", icon: <FaStethoscope /> },
  { id: 32, text: "Food & Beverage", icon: <FaUtensils /> },
  { id: 33, text: "Chemicals", icon: <FaFlask /> },
  {
    id: 34,
    text: "Testing Instrument & Equipment",
    icon: <FaClipboardCheck />,
  },
  { id: 35, text: "Security", icon: <FaShieldAlt /> },
  { id: 36, text: "Pet Supplies", icon: <FaDog /> },
  { id: 37, text: "Fabric & Textile Raw Material", icon: <FaCogs /> },
  { id: 38, text: "Metals & Alloys" },
  { id: 39, text: "Safety", icon: <FaHardHat /> },
  { id: 40, text: "Material Handling", icon: <FaShippingFast /> },
  { id: 41, text: "Buyer's Logistic Services Market", icon: <FaRecycle /> },
  { id: 42, text: "Rubber & Plastics", icon: <FaCog /> },
  { id: 43, text: "Power Transmission", icon: <FaPlug /> },
  { id: 44, text: "Fabrication Services", icon: <FaCogs /> },
  { id: 45, text: "Agriculture", icon: <FaSeedling /> },
];

export default carouselItems;
